#
# Zsh aliases
#

# Commands
alias ls='ls -aF'
alias refresh='source ~/.zshrc'
alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO'
#alias upDots='cp ~/.zshrc ~/.dotfiles/.zsh && cp ~/.oh-my-zsh/custom/aliases.zsh ~/.dotfiles/.zsh && cp ~/.oh-my-zsh/custom/prompt.zsh ~/.dotfiles/.zsh && cp ~/Library/Application\ Support/atomime\ Text\ 2/Packages/User/Preferences.sublime-settings ~/.dotfiles/.sublime && cp ~/.emmet/snippets.json ~/.dotfiles/.emmet && git add ~/.dotfiles/* && git commit ~/.dotfiles/ -m "auto updating config files" && git push'
alias serve='http-server .'
alias serveo='http-server . -o'
alias gs='git status'
alias gd='git diff'
alias gf='git fetch'
alias gpl='git pull'
alias gps='git push'
alias ga='git add'
alias gcm='git commit -m'
alias gpretty="git log --all --graph --pretty=format:'%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"

# Applications
alias ffdev='open -a Firefox\ Developer\ Edition'
alias safari='open -a Safari'
alias chrome='open -a Google\ Chrome'
#alias opera='open -a Opera'
#alias breach='open -a Breach'
alias preview='open -a Preview'
alias itunes='open -a iTunes'
alias gimp='open -a GIMP'
alias dash='open -a Dash'
#alias weka='open -a weka-3-6-12-oracle-jvm'
alias rstudio='open -a RStudio'
alias airport='open -a AirPort\ Utility'
#alias torrent='open -a Transmission'
alias xld='open -a XLD'
alias protege='sh /Applications/Protege-5.0.0-beta-24/run.command'
alias email='open -a Microsoft\ Outlook'
alias ink='open -a Inkscape'
alias photos='open -a Photos'
alias excel='open -a Microsoft\ Excel'
alias word='open -a Microsoft\ Word'
alias ppt='open -a Microsoft\ PowerPoint'
alias spot='open -a Spotify'
alias slack='open -a Slack'

# Files
alias zconfig='code ~/.zshrc'
alias zalias='code ~/.oh-my-zsh/custom/aliases.zsh'
alias zprompt='code ~/.oh-my-zsh/custom/prompt.zsh'
#alias dots='~/.dotfiles/'
alias changelog='code ~/Documents/About\ This\ Mac/changelog.md'
alias emmet='code ~/.emmet/snippets.json'
alias bobo='nano ~/Documents/bk_arrivals.csv'
alias notes='code ~/Documents/OneDrive\ -\ University\ of\ Maryland\ Baltimore/DAILY_TASK_NOTES/open.md && atom ~/Documents/OneDrive/OneDrive\ -\ University\ of\ Maryland\ Baltimore/DAILY_TASK_NOTES/closed.md'
